# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [3]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False
if numbers_x[0] == numbers_x[len(numbers_x)-1]:
    print("true")
else:
    print("false")
if numbers_y[0] == numbers_y[len(numbers_y)-1]:
    print("true")
else:
    print("false")

true
false






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [10]:
#code here
import numpy as np
array_1 = [1,2,3,4,5,6,7,8,9,10,11,12]
array_1 = np.array(array_1)
array_2 = [1,2,3,4,5,6,7,8,9,10,11,12]
array_2 = np.array(array_2)
sum = array_1 + array_2
print("sum" , sum)
prod = array_1 * array_2
print("product" , prod)


sum [ 2  4  6  8 10 12 14 16 18 20 22 24]
product [  1   4   9  16  25  36  49  64  81 100 121 144]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [20]:
#code here
array_1 = [1,2,3,4,5,6,7,8,9,10,11,12]
array_1 = np.array(array_1)
array_2D_1 = array_1.reshape(3,4)
array_2 = [1,2,3,4,5,6,7,8,9,10,11,12]
array_2 = np.array(array_2)
array_2D_2 = array_2.reshape(3,4)
print("2D array from 1D array\n" , array_2D_1)
concate_h = np.concatenate((array_2D_1,array_2D_2),1)
print("horizental concatinate \n",concate_h)
concate_v = np.concatenate((array_2D_1,array_2D_2),0)
print("horizental concatinate \n",concate_v)

2D array from 1D array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
horizental concatinate 
 [[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]
horizental concatinate 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [9]:
#Code here
shopping_cart = []
print("-----WELCOME FOR SHOPPING------\n")
products = ["1. sugar","2. eggs","3. cake"]
price = [250,360,200]
print("availible product : ",products)
while(True):
    user = input("\nENTER number corresponding to product and if you want to quit press q\n")
    if user.lower() == "q":
        break
    else:
        user = int(user)-1
        if user <= 3:
            print("Product added to your cart\n")
            shopping_cart.append(user)
        else:
            print("product not availible\n")
total = 0
if len(shopping_cart) != 0:
    print("products added to your cart are : ")
    for i in range(len(shopping_cart)):
        print(products[shopping_cart[i]],"---",price[shopping_cart[i]])
        total+=price[shopping_cart[i]]
    print("Total Amount : " , total)
else:
    print("your shopping cart is empty\n")
print("-----GOOD BYE------")

-----WELCOME FOR SHOPPING------

availible product :  ['1. sugar', '2. eggs', '3. cake']



ENTER number corresponding to product and if you want to quit press q
 1


Product added to your cart




ENTER number corresponding to product and if you want to quit press q
 2


Product added to your cart




ENTER number corresponding to product and if you want to quit press q
 2


Product added to your cart




ENTER number corresponding to product and if you want to quit press q
 3


Product added to your cart




ENTER number corresponding to product and if you want to quit press q
 q


products added to your cart are : 
1. sugar --- 250
2. eggs --- 360
2. eggs --- 360
3. cake --- 200
Total Amount :  1170
-----GOOD BYE------


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [84]:
#code here
from nltk import word_tokenize
important = ["important","importance","significance","useful", "deadline" , "timeline" ,
             "datesheet" , "data" , "friend" , "sir" , "student" , "teacher" ,
             "university", "business" , "verification" , "verify" , "code"]
spam = ["Cash bonus" , "Cents on the dollar" , "Double your cash" , "Earn extra cash",
       "Free consultation" , "Free investment" , "Free membership" , "Increase sales",
       "Pure profit" , "Apply now" , "Order now"]
promotion = ["sales" , "product" "beautiful" , "advertising" , "publicity" , "localizing",
            "promoting" , "clinet" , "customer" , "market" , "shop" , "price"]
def classify_emails(email):
    tokens = word_tokenize(email)
    for i in email:
        if i in important:
            print("This email is important")
            break
        if i in spam:
            print("This email is spam")
            break
        if i in promotion:
            print("This email is promotion")
            break

for i in emails:
    classify_emails(i)
    

ModuleNotFoundError: No module named 'nltk'

# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [83]:
#code here
dictionary = { "hello" : "hola" , "love" : "amor" , "happiness" : "falicidad",
           "cat" : "gato" , "dog" : "perro" , "smile":"sonerier" , "yes" : "si"}
while(True):
    user = input("enter the word to translate in spanish or enter q to exit")
    if user == "q":
        break
    else:
        if user in dictionary:
            print(dictionary[user])
        else: 
            print("word not availible")
print("----GOOD BYE-----")

enter the word to translate in spanish or enter q to exit hello


hola


enter the word to translate in spanish or enter q to exit q


----GOOD BYE-----


# Lab Task 07

In [10]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv")
data.head(10)

/tmp/ipykernel_6210/2778003234.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


Rank                       Name Platform    Year         Genre Publisher  \
0     1                 Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2          Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3             Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4          Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5   Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   
5     6                     Tetris       GB  1989.0        Puzzle  Nintendo   
6     7      New Super Mario Bros.       DS  2006.0      Platform  Nintendo   
7     8                   Wii Play      Wii  2006.0          Misc  Nintendo   
8     9  New Super Mario Bros. Wii      Wii  2009.0      Platform  Nintendo   
9    10                  Duck Hunt      NES  1984.0       Shooter  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37  
5     23.20      2.26      4.22         0.58         30.26  
6     11.38      9.23      6.50         2.90         30.01  
7     14.03      9.20      2.93         2.85         29.02  
8     14.59      7.06      4.70         2.26         28.62  
9     26.93      0.63      0.28         0.47         28.31

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [91]:
# -------- Toatal GB sales --------------
total_GB_sales = data["Global_Sales"].sum()
print("Total global sales ",total_GB_sales)

Total global sales  8920.44


In [90]:
# ---------- Game with highest global sales ---------------
max = data["Global_Sales"].max()
highest_GB_game = data[data["Global_Sales"] == max].Name
print("Game with highest global sales : " , highest_GB_game  )

Game with highest global sales :  0    Wii Sports
Name: Name, dtype: object


In [89]:
# average sale for all ----------------
print("average for NA_Sales" , data["NA_Sales"].mean()) 
print("average for EU_Sales",data["EU_Sales"].mean())
print("average for JP_Sales",data["JP_Sales"].mean())
print("average for Other_Sales",data["Other_Sales"].mean())

average for NA_Sales 0.26466742981082064
average for EU_Sales 0.14665200626581515
average for JP_Sales 0.077781660441017
average for Other_Sales 0.0480630196409206


In [88]:
#------- The TOP 5 genre ---------
df = data.sort_values(by=['Global_Sales'])
print("The TOP 5 genre are : ")
df.Genre.head(5)

The TOP 5 genre are : 


16597     Platform
16188         Misc
16187       Puzzle
16186     Strategy
16185    Adventure
Name: Genre, dtype: object

In [87]:
# ---------- most popular genre according to NA_sales --------------
df1 = data.sort_values(by=['NA_Sales'])
print("most popular genre according to NA_sales is : ")
df.Genre.head(1)

most popular genre according to NA_sales is : 


16597    Platform
Name: Genre, dtype: object

In [75]:
df2 = data.groupby("Genre").sum()
df2

Rank                                               Name  \
Genre                                                                       
Action        26441383  Grand Theft Auto VGrand Theft Auto: San Andrea...   
Adventure     14831165  Super Mario Land 2: 6 Golden CoinsAssassin's C...   
Fighting       6484242  Super Smash Bros. BrawlSuper Smash Bros. for W...   
Misc          14889052  Wii PlayKinect Adventures!Brain Age: Train You...   
Platform       6137545  Super Mario Bros.New Super Mario Bros.New Supe...   
Puzzle         5603136  TetrisBrain Age 2: More Training in Minutes a ...   
Racing         9943933  Mario Kart WiiMario Kart DSGran Turismo 3: A-S...   
Role-Playing  12032228  Pokemon Red/Pokemon BluePokemon Gold/Pokemon S...   
Shooter        9653872  Duck HuntCall of Duty: Modern Warfare 3Call of...   
Simulation     7478816  NintendogsAnimal Crossing: Wild WorldAnimal Cr...   
Sports        17419112  Wii SportsWii Sports ResortWii FitWii Fit Plus...   
Strategy       6858962  Pokemon StadiumWarzone 2100StarCraft II: Wings...   

                                                       Platform       Year  \
Genre                                                                        
Action        PS3PS2X360PS2PS2PS4DSX360PS3PS3PSPN64WiiPS3PS3...  6531731.0   
Adventure     GBX360PS3NESPSPS3DSPS3PCX360PCGBAPS2GBPSGCGBPS...  2562375.0   
Fighting      Wii3DSPSGCSNESPSN64WiiUPS3SNESPS2PS2PSPS2PSPSS...  1675871.0   
Misc          WiiX360DSWiiWiiX360DSWiiWiiWiiWiiDSPS3GBPS2PS2...  3432412.0   
Platform      NESDSWiiSNESGBNESN64Wii3DSSNESDS3DSSNESWiiPSNE...  1755347.0   
Puzzle        GBDS2600NESGBDSNESDSDSGBAWiiDSDSPSDSDSDSDSPS2D...  1144994.0   
Racing        WiiDSPS23DSPS2PSPS3N64PSSNESPS2WiiUGCPS2X360GB...  2457934.0   
Role-Playing  GBGBDSGBADSGB3DS3DSGBAPSX360DSPS2PSDSPS4PS3GBA...  2952379.0   
Shooter       NESX360X360PS4PS3X360X360PS3PS3X360PS3X360X360...  2571588.0   
Simulation    DSDS3DSPCDS3DSPCWii3DSPCDSN64DSPS2GCPC3DSPCWii...  1707589.0   
Sports        WiiWiiWiiWiiPS4WiiPS3WiiPS3PS4X360PS2DSPS3PSPS...  4620621.0   
Strategy      N64PSPCPCGBPCN64X360PCPCPCGBAPCPCGCGBPCDSPCPCN...  1345757.0   

                                                      Publisher  NA_Sales  \
Genre                                                                       
Action        Take-Two InteractiveTake-Two InteractiveTake-T...    877.83   
Adventure     NintendoUbisoftUbisoftNintendoTHQTake-Two Inte...    105.80   
Fighting      NintendoNintendoSony Computer EntertainmentNin...    223.59   
Misc          NintendoMicrosoft Game StudiosNintendoUbisoftU...    410.24   
Platform      NintendoNintendoNintendoNintendoNintendoNinten...    447.05   
Puzzle        NintendoNintendoAtariNintendoNintendoNintendoN...    123.78   
Racing        NintendoNintendoSony Computer EntertainmentNin...    359.42   
Role-Playing  NintendoNintendoNintendoNintendoNintendoNinten...    327.28   
Shooter       NintendoActivisionActivisionActivisionActivisi...    582.60   
Simulation    NintendoNintendoNintendoElectronic Arts505 Gam...    183.31   
Sports        NintendoNintendoNintendoNintendoElectronic Art...    683.35   
Strategy      NintendoEidos InteractiveActivisionActivisionN...     68.70   

              EU_Sales  JP_Sales  Other_Sales  Global_Sales  
Genre                                                        
Action          525.00    159.95       187.38       1751.18  
Adventure        64.13     52.07        16.81        239.04  
Fighting        101.32     87.35        36.68        448.91  
Misc            215.98    107.76        75.32        809.96  
Platform        201.63    130.77        51.59        831.37  
Puzzle           50.78     57.31        12.55        244.95  
Racing          238.39     56.69        77.27        732.04  
Role-Playing    188.06    352.31        59.61        927.37  
Shooter         313.27     38.28       102.69       1037.37  
Simulation      113.38     63.70        31.52        392.20  
Sports          376.85 

In [43]:
data.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [44]:
print("The TOP 3 gaming Platform are : ")
df.Platform.head(3)

The TOP 3 gaming Platform are : 


16597    GBA
16188    PS3
16187     PC
Name: Platform, dtype: object

In [86]:
# ---------------Market share ----------------------
share = df2["Global_Sales"]
total = df2["Global_Sales"].sum()
for i in range(12):
    print("Market share is : ",(share.iloc[i]/total)*100 , "%")


Market share is :  19.63109443031958 %
Market share is :  2.6796884458614145 %
Market share is :  5.0323750846370805 %
Market share is :  9.079821174740259 %
Market share is :  9.319831757177896 %
Market share is :  2.7459407831900666 %
Market share is :  8.206321661263345 %
Market share is :  10.396011855917422 %
Market share is :  11.629134885723124 %
Market share is :  4.396644111725431 %
Market share is :  14.920003945993695 %
Market share is :  1.9631318634506818 %


In [85]:
# ------------------ correlation -----------------------
data[["NA_Sales","EU_Sales"]].corr()

NA_Sales  EU_Sales
NA_Sales  1.000000  0.767727
EU_Sales  0.767727  1.000000